server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://10.140.0.6:3306/jiwell?serverTimezone=CST&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567890
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  redis:
    host: redis
  rabbitmq:
    host: rabbit
    username: /ji-well
    password: ji-well
    virtual-host: /ji-well
    template:
      retry:
        enabled: true
        multiplier: 2
        initial-interval: 10000ms
        max-interval: 210000ms
      exchange: jiwell.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://10.140.0.10:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

ribbon:
  ConnectTimeout: 40000000 # 连接超时时间(ms)
  ReadTimeout: 20000000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000000 # 熔断超时时长：10000ms
feign:
  client:
    config:
      default:
        connect-timeout: 100000
        read-timeout: 100000
