server:
  port: 8087
spring:
  application:
    name: auth-service
  rabbitmq:
    virtual-host: /ji-well
    username: /ji-well
    password: ji-well
    host: 10.140.0.9
eureka:
  client:
    service-url:
      defaultZone: http://10.140.0.10:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 10.140.0.10 #這個在Docker上不能使用127.0.0.1 會抓不到
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳
jiwell:
  jwt:
    secret: jiwell@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: /mydata/rsa/rsa.pub # 公钥地址
    priKeyPath: /mydata/rsa/rsa.pri # 私钥地址
    expire: 3000 # 过期时间,单位分钟 token 過期時間
    cookieName: LY_TOKEN
    cookieMaxAge: 3000 #cokkie 過期時間 單位秒

ribbon:
  ConnectTimeout: 10000 # 连接超时时间(ms)
  ReadTimeout: 5000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
