server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://35.236.155.182:3306/jiwell?serverTimezone=CST&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567890
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  redis:
    host: 35.236.155.182
  rabbitmq:
    host: 35.236.155.182
#    host: 127.0.0.1
    username: /ji-well
    password: ji-well
    virtual-host: /ji-well
    template:
      retry:
        enabled: true
        max-interval: 210000ms
        initial-interval: 10000ms
        multiplier: 2
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
mybatis:
  type-aliases-package: com.jiwell.user.pojo
