server:
  port: 10011
spring:
  application:
    name: wsirius-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuuhaokun/wsirius-config.git
  rabbitmq:
    host: 10.140.0.9
    username: /ji-well
    password: ji-well
    virtual-host: /ji-well


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
