server:
  port: 8092
  tomcat:
    max-connections: 5000
spring:
  application:
    name: comments-service
  data:
    mongodb:
      host: 10.140.0.6
      database: jiwelldb
  datasource:
    url: jdbc:mysql://10.140.0.6:3306/jiwell?serverTimezone=CST&characterEncoding=UTF-8&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567890
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  rabbitmq:
    virtual-host: /ji-well
    username: /ji-well
    password: ji-well
    host: rabbit
  redis:
    host: redis
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
eureka:
  client:
    service-url:
      defaultZone: http://10.140.0.10:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 10.140.0.10
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳
ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

jiwell:
  worker:
    workerId: 2
    dataCenterId: 2
  jwt:
    cookieName: LY_TOKEN
    pubKeyPath: /mydata/rsa/rsa.pub # 公钥地址
