server:
  port: 10011
spring:
  profiles:
    active: prod #默认为开发环境
  application:
    name: wsirius-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuuhaokun/wsirius-config.git
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
